[build]
# choose wich target compile
# target = "x86_64-lzos.json"
target = "riscv64gc-unknown-none-elf"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt --no-reboot -monitor stdio -kernel"
